# Generated by Django 4.0.6 on 2022-07-22 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email_id', models.EmailField(max_length=254)),
                ('company_code', models.CharField(blank=True, max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2}[0-9]{2}[E|N]$', 'Only alphanumeric characters are allowed.')])),
                ('strength', models.PositiveIntegerField(null=True)),
                ('website', models.URLField(max_length=1200, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
